language: python

matrix:
  include:
    - python: 3.6

cache:
  pip: true

env:
  global:
    - PATH=$HOME/bin:$PATH

before_script:
  - mkdir -p ~/bin
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar jvxf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - rm ~/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - mv ~/phantomjs-2.1.1-linux-x86_64/bin/phantomjs ~/bin
  - chmod +x ~/bin/phantomjs

install:
  - pip install -r tests/requirements.txt

script:
  - travis_retry travis_retry travis_retry tox

sudo: false
